# Generated by Django 3.2.6 on 2021-08-08 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='catagory',
            name='files',
            field=models.ManyToManyField(to='contents.Multimedia'),
        ),
    ]
