# Generated by Django 3.2.6 on 2021-08-08 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0002_catagory_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='files',
            field=models.ManyToManyField(to='contents.Multimedia'),
        ),
    ]
