# Generated by Django 3.2.6 on 2021-08-16 13:00

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0004_multimedia_is_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('files', models.ManyToManyField(to='contents.Multimedia')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='content',
            name='catagory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contents.category'),
        ),
        migrations.DeleteModel(
            name='Catagory',
        ),
    ]
