# Generated by Django 3.2.6 on 2021-08-16 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0006_rename_catagory_content_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='files',
            field=models.ManyToManyField(blank=True, null=True, to='contents.Multimedia'),
        ),
    ]
