# Generated by Django 3.2.7 on 2021-10-18 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0008_auto_20211018_1510'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='content',
            options={'verbose_name': 'content', 'verbose_name_plural': 'contents'},
        ),
        migrations.AlterModelOptions(
            name='multimedia',
            options={'verbose_name': 'multimedia', 'verbose_name_plural': 'multimedia'},
        ),
        migrations.AlterField(
            model_name='content',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='contents.category'),
        ),
    ]
