# Generated by Django 3.2.7 on 2021-10-18 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0009_auto_20211018_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='files',
            field=models.ManyToManyField(blank=True, to='contents.Multimedia'),
        ),
    ]
