FROM dockerhub.ir/python:3.9

RUN useradd -ms /bin/bash motem
WORKDIR /home/motem/app
USER motem

ENV PATH="$PATH:/home/motem/.local/bin"
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
RUN python -m pip install --upgrade pip

COPY ./requirements.txt ./

RUN pip install -r requirements.txt
COPY . .