from .create import MultimediaCreateReqSerializer,MultimediaCreateResSerializer
from .list import MultimediaListResSerializer
from .retrieve import MultimediaRetrieveResSerializer
from .update import MultimediaUpdateReqSerializer,MultimediaUpdateResSerializer 